import type { Metadata } from 'next';

import '../styles/globals.css';

import { Nanum_Gothic } from 'next/font/google';

import Navbar from '@/widgets/navbar';

const nanumGothic = Nanum_Gothic({
  variable: '--font-nanum-gothic',
  subsets: ['latin'], // 필요한 문자 집합 (한글 지원 필요 시 추가)
  weight: ['400', '700'], // 사용할 폰트 가중치 명시
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nanumGothic.variable} font-nanum antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
